plugins {
    id 'org.jetbrains.kotlin.jvm' version '2.2.20'
    id 'org.jetbrains.intellij.platform' version '2.9.0'
    id 'org.jetbrains.grammarkit' version '2023.3.0.4'
}

kotlin {
    jvmToolchain(21)
    compilerOptions {
        freeCompilerArgs.add('-Xjvm-default=all')
    }
}

idea.module.generatedSourceDirs += file('gen')

sourceSets.main.java.srcDirs += 'gen'

repositories {
    mavenCentral()

    intellijPlatform {
        defaultRepositories()
    }
}

dependencies {
    intellijPlatform {
        intellijIdeaCommunity('2024.3.5')
        testFramework(org.jetbrains.intellij.platform.gradle.TestFrameworkType.Platform.INSTANCE)
    }

    testImplementation 'junit:junit:4.13.2'
    testRuntimeOnly 'org.opentest4j:opentest4j:1.3.0'
}

intellijPlatform {
    pluginConfiguration {
        name = 'Scilla'

        ideaVersion {
            sinceBuild = '243'
            untilBuild = provider { null }
        }
    }
}

tasks.named('generateLexer', org.jetbrains.grammarkit.tasks.GenerateLexerTask) {
    sourceFile = file("$projectDir/src/main/kotlin/com/zloyrobot/scilla/lang/_ScillaLexer.flex")
    targetOutputDir = file("$projectDir/gen/com/zloyrobot/scilla/lexer")
    purgeOldFiles = true
}

tasks.named('compileKotlin') {
    dependsOn 'generateLexer'
}

tasks.named('test') {
    useJUnit()
}
